# Generated by Django 3.1.7 on 2021-03-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compradores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('longitud', models.FloatField(max_length=50)),
                ('latitud', models.FloatField(max_length=50)),
                ('estado_geo', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
